---
title: "Longitudinal pipeline 3 time point tutorial"
author: "fanzhang labs"
date: "2025-10-09"
output: html_document
---




## 
Any data can be used for the longitudinal pipeline, but for this example, we will simulate a longitudinal dataset






```{r}
dummy_data <- generate_dummy_data_time(
  n_cells                    = 150,
  sd_celltypes               = 0.1,
  n_major_cell_types         = 7,
  n_minor_cell_types         = 3,
  relative_abundance         = 0.4,
  n_major_interact_celltypes = 2,
  n_minor_interact_celltypes = 2,
  n_individuals              = 30,
  n_batchs                   = 4,
  interaction_feature        = "visit",
  time_points                = 3,
  test_var                   = "disease",
  prop_disease               = 0.5,
  fc_interact                = 0.6,
  interaction_type           = "specific",
  seed                       = 2020,
  visit_effects_progressor   = c(0.00, 0.30, 0.60),
  visit_effects_control      = c(0, 0, 0),
  direction_by_cluster       = c(+1, -1, +1, -1)
)
    
    

    
    
```


Generate PCS, these are derived from the gene expression followed by any dimension reduction technique.

```{r}
pcs = generate_pseudo_pcs_time (
  dummy_data,
  n_pcs = 20,

  cluster_pcs = 1:20,
  disease_pcs = 0,
  sex_pcs = 0,
  age_pcs = 0,
  bmi_pcs = 0,
  batch_pcs = 0,
  interaction_pcs = 0,
  visit_pcs = 0,
  subject_pcs = 0,

  scale_factor = 5,

  cluster_ratio = 0.8,
  disease_ratio = 0,
  sex_ratio = 0,
  age_ratio = 0,
  bmi_ratio = 0,
  batch_ratio = 0,
  visit_ratio = 0,
  interaction_ratio = 0,
  subject_ratio = 0,

  cluster_col = "cell_type",
  disease_col = "disease",
  sex_col = "sex",
  age_col = "age",
  bmi_col = "bmi",
  batch_col = "batch",
  visit_col = "visit",
  interact_term_col = "interact_term",
  seed = 2020
)

head(pcs)
```



```{r}

obj = scLASER(metadata = dummy_data, pcs = pcs)
obj
```



```{r}
obj <- compute_umap(obj, n_neighbors = 30, metric = "cosine", min_dist = 0.01)

```


```{r}
    

 plot_celltype_proportions(obj) 
    
```





```{r}
obj <- run_harmony(obj, batch_col = "sample_id", theta = 2,
                                      # lambda = 1,
                                      # tau = 10, 
                                      epsilon.cluster = -Inf,
                                      epsilon.harmony = -Inf,
                                      max.iter.cluster = 30,
                                      max.iter.harmony = 10,
                                      plot_convergence = F)


```


```{r}



obj = association_nam_scLASER (object = obj,
  test_var          = "test_var_cna",
  samplem_key       = "subject_id",
  graph_use         = "RNA_nn",
  batches           = "batch",
  covs              = c("age", "sex"),
  nsteps            = NULL,
  verbose           = TRUE,
  assay             = NULL,
  key               = "NAMPC_",
  maxnsteps         = 15L,
  max_frac_pcs      = 0.15,
  ks                = NULL,
  Nnull             = 1000,
  force_permute_all = FALSE,
  local_test        = TRUE,
  seed              = 1234,
  return_nam        = F
)

saveRDS(obj,"sclaser_obj.rds")
```



```{r}
rownames(obj@nam_pcs) = obj@metadata$sample_id
obj = longAnalyses_plusModelSelection_scLASER(obj ,
                                              disease_var = "disease",
                                              subject_var ="subject_id",
                                              sample_var="sample_id",
                                              time_var =  "visit",
                                              covariates = c("age", "sex"))
```



```{r}
obj@pipeline_output
```

